name: Naruto/Boruto Facts Bot

# Schedule: approx every 85 minutes (0 and 25 past the hour)
on:
  schedule:
    - cron: '0 * * * *'
    - cron: '25 * * * *'
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run Naruto/Boruto Facts Bot
      - name: Run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: |
          python bot.py

      # 5. Commit updated facts.json back to repo using PAT_TOKEN
      - name: Commit updated facts.json
        env:
            PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git

          git add facts.json
          git commit -m "Update posted facts [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

